#!/usr/bin/env python3
"""Generate the exact hash-complete Python lock used by the DT4 oracle."""

import argparse
import json
import urllib.request
from pathlib import Path

PACKAGES = {
    "certifi": "2026.7.22",
    "charset-normalizer": "3.5.1",
    "coloredlogs": "15.0.1",
    "colorama": "0.4.6",
    "einops": "0.8.1",
    "filelock": "3.32.3",
    "fsspec": "2026.7.0",
    "flatbuffers": "25.12.19",
    "huggingface-hub": "0.36.2",
    "humanfriendly": "10.0",
    "idna": "3.19",
    "jinja2": "3.1.6",
    "markupsafe": "3.0.3",
    "mpmath": "1.3.0",
    "networkx": "3.6.1",
    "numpy": "2.3.2",
    "onnxruntime": "1.22.1",
    "packaging": "26.3",
    "pyyaml": "6.0.3",
    "protobuf": "7.36.0",
    "pyreadline3": "3.5.6",
    "regex": "2026.7.19",
    "requests": "2.34.2",
    "safetensors": "0.5.3",
    "setuptools": "84.0.0",
    "sympy": "1.14.0",
    "tokenizers": "0.21.2",
    "torch": "2.7.1",
    "tqdm": "4.70.0",
    "transformers": "4.53.3",
    "typing-extensions": "4.16.0",
    "urllib3": "2.7.0",
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    lines = [
        "# Generated by scripts/dt4_generate_requirements_lock.py for CPython 3.13.14.",
        "# Every published distribution of each exact version is covered by SHA-256.",
    ]
    for package, version in sorted(PACKAGES.items()):
        with urllib.request.urlopen(f"https://pypi.org/pypi/{package}/{version}/json") as response:
            metadata = json.load(response)
        hashes = sorted({item["digests"]["sha256"] for item in metadata["urls"]})
        if not hashes:
            raise RuntimeError(f"PyPI returned no artifacts for {package}=={version}")
        lines.append(f"{package}=={version} \\")
        for index, digest in enumerate(hashes):
            suffix = " \\" if index + 1 < len(hashes) else ""
            lines.append(f"    --hash=sha256:{digest}{suffix}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as output:
        output.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
